FROM nix-docker.registry.twcstorage.ru/base/redhat/ubi9-minimal:9.6
# Update packages
RUN microdnf -y update
# Install prerequisites
RUN microdnf -y install openssl git tar gzip
# Install helm
WORKDIR /etc/
RUN mkdir -p /etc/helm
RUN curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
RUN chmod 700 get_helm.sh
RUN ./get_helm.sh
WORKDIR /etc/
RUN rm -rf /helm
# Install kubectl
RUN mkdir /etc/kubectldir
RUN curl -LO "https://dl.k8s.io/release/v1.34.0/bin/linux/amd64/kubectl"
RUN install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
WORKDIR /etc/
RUN rm -rf /kubectldir
CMD [ "kubectl", "version", "--client", "--output=yaml"]